#ifndef VERSION_H
#define VERSION_H

#ifndef VERSION_STR_POSTFIX
#define VERSION_STR_POSTFIX ""
#endif /* VERSION_STR_POSTFIX */

#ifndef GIT_VERSION_STR_POSTFIX
#define GIT_VERSION_STR_POSTFIX ""
#endif /* GIT_VERSION_STR_POSTFIX */

#define LAIRD_VER_STR "-Laird-70.12.0.11"
#define VERSION_STR "2.10-devel" LAIRD_VER_STR VERSION_STR_POSTFIX GIT_VERSION_STR_POSTFIX

#endif /* VERSION_H */
